version: '3.8'

services:
  node-engine:
    image: service-engine
    build:
      context: .
      dockerfile: ./Engine-search-service/deploy/develop/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./Engine-search-service:/app
    tty: true
    entrypoint: ["/bin/bash", "-c"]
    command: ["npm ci && npm run build && npm run start:dev"]