version: '3.8'

services:
  elastic-search:
    image: elasticsearch:8.5.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - ${ELASTIC_PORT}:${ELASTIC_PORT}
    volumes:
      - dataes01:/usr/share/elasticsearch/data
    env_file:
      - .env
  node-engine:
    image: service-engine
    build:
      context: .
      target: production
      dockerfile: ./Engine-search-service/deploy/production/Dockerfile
    env_file:
      - .env
    depends_on:
      - elastic-search
    networks:
      - es-net
    ports:
      - ${ENGINE_SEARCH_PORT}:${ENGINE_SEARCH_PORT}
    command: npm run start:prod
    restart: always

volumes:
  dataes01:
    driver: local
networks:
  es-net:
    driver: bridge
