version: '3.8'

services:
  node-engine:
    image: service-engine
    build:
      context: .
      target: production
      dockerfile: ./Engine-search-service/deploy/production/Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    restart: always